import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createCloud,memoryStorage} from './fake-firestore.mjs';

const modulePath=process.env.FINALIZER_MODULE || new URL('../local-receiving.js',import.meta.url);
const root=['artifacts','tnuva-app-classic','public','data'];
const record=id=>root.concat('receipts',id).join('/');
const product=id=>root.concat('products',id).join('/');
let sequence=0;
function harness({cloud=createCloud(),storage=memoryStorage(),device='red-phone',fp='fingerprint-one',session='receipt-one'}={}) {
  const context=vm.createContext({console,JSON,Date,setTimeout,clearTimeout,navigator:{onLine:true},crypto:{randomUUID:()=>`red-${++sequence}`}});
  vm.runInContext(fs.readFileSync(modulePath,'utf8'),context);
  const client=cloud.client();
  const state={fp,session};
  const engine=context.LocalReceiving.create({storage,prefix:'tn',app:'tnuva',db:client.db,fs:client.fs,rootPath:root,
    makeId:()=>`red-${++sequence}`,deviceName:()=>device,appVersion:139,getFingerprint:()=>state.fp,getSession:()=>state.session,timeoutMs:40});
  const input={sessionId:session,recordId:'receipt-one',data:{timestamp:100,operationId:'receipt-one',items:[{productId:'milk',qty:9}],count:1},expected:null,prices:[],fingerprint:fp};
  return {engine,cloud,client,storage,state,input,finish:(overrides={})=>engine.finish({...input,...overrides})};
}

test('no cloud activity until final save',()=>{const p=harness();assert.equal(p.cloud.transactions,0);assert.equal(p.client.listenerCount(),0);assert.equal(p.cloud.server.size,0);});
test('first final save writes exactly one receipt, repeat cannot duplicate',async()=>{const p=harness();assert.equal((await p.finish()).ok,true);const saved=p.cloud.get(record('receipt-one'));assert.equal(saved.items[0].qty,9);const result=await p.finish();assert.equal(p.cloud.paths('/receipts/').length,1);assert.equal(p.cloud.get(record('receipt-one')).items[0].qty,9);assert.ok(result.ok || result.reason);});
test('preexisting other receipt never overwritten',async()=>{const p=harness();p.cloud.put(record('receipt-one'),{items:[{qty:71}],operationId:'receipt-one'});assert.equal((await p.finish()).ok,false);assert.equal(p.cloud.get(record('receipt-one')).items[0].qty,71);assert.equal(p.cloud.paths('/actionLog/').length,0);});
test('remote price change prevents all final writes',async()=>{const p=harness();p.cloud.put(product('milk'),{name:'milk',price:7});assert.equal((await p.finish({prices:[{id:'milk',expected:5,price:6}]})).ok,false);assert.equal(p.cloud.get(record('receipt-one')),null);assert.equal(p.cloud.get(product('milk')).price,7);assert.equal(p.cloud.paths('/actionLog/').length,0);});
test('deleted product prevents all final writes',async()=>{const p=harness();assert.equal((await p.finish({prices:[{id:'milk',expected:5,price:6}]})).ok,false);assert.equal(p.cloud.get(record('receipt-one')),null);assert.equal(p.cloud.paths('/actionLog/').length,0);});
test('price update receipt and audit commit atomically',async()=>{const p=harness();p.cloud.put(product('milk'),{name:'milk',price:5,barcode:'123'});assert.equal((await p.finish({prices:[{id:'milk',expected:5,price:6}]})).ok,true);assert.equal(p.cloud.get(record('receipt-one')).items[0].qty,9);assert.equal(p.cloud.get(product('milk')).price,6);assert.equal(p.cloud.get(product('milk')).barcode,'123');assert.equal(p.cloud.paths('/actionLog/').length,1);});
test('changed attached record refuses overwrite and keeps newer linked credit',async()=>{const p=harness({session:'edit-one'});const expected={items:[{qty:5}],shortCreditUnits:1};p.cloud.put(record('receipt-one'),{...expected,shortCreditUnits:2});assert.equal((await p.finish({expected})).ok,false);assert.equal(p.cloud.get(record('receipt-one')).shortCreditUnits,2);});
test('deleted attached record cannot resurrect',async()=>{const p=harness({session:'edit-one'});assert.equal((await p.finish({expected:{items:[{qty:5}]}})).ok,false);assert.equal(p.cloud.get(record('receipt-one')),null);});
test('attach ignores synthetic top-level id only',async()=>{const p=harness({session:'edit-one'});const expected={id:'receipt-one',items:[{qty:5}],shortCreditUnits:1};p.cloud.put(record('receipt-one'),{items:[{qty:5}],shortCreditUnits:1});assert.equal((await p.finish({expected,data:{items:[{qty:9}],shortCreditUnits:1}})).ok,true);assert.equal(p.cloud.get(record('receipt-one')).items[0].qty,9);});
test('concurrent phones using same receipt id cannot both replace content',async()=>{const cloud=createCloud(),a=harness({cloud,device:'A'}),b=harness({cloud,device:'B',fp:'different-fingerprint'});let release;cloud.commitGate=new Promise(r=>release=r);const pa=a.finish(),pb=b.finish({data:{items:[{qty:17}]}});await new Promise(r=>setTimeout(r,5));release();const results=await Promise.all([pa,pb]);assert.equal(results.filter(r=>r.ok).length,1);assert.equal(cloud.paths('/receipts/').length,1);assert.equal(cloud.paths('/actionLog/').length,1);});
test('changed local fingerprint while committing cannot produce cleanup success',async()=>{const p=harness();let release;p.cloud.commitGate=new Promise(r=>release=r);const pending=p.finish();await new Promise(r=>setTimeout(r,5));p.state.fp='later-unsubmitted-content';release();assert.equal((await pending).ok,false);assert.equal(p.cloud.get(record('receipt-one')).items[0].qty,9);});
test('same fingerprint but new active session while committing cannot clear new receipt',async()=>{const p=harness();let release;p.cloud.commitGate=new Promise(r=>release=r);const pending=p.finish();await new Promise(r=>setTimeout(r,5));p.state.session='receipt-two';release();assert.equal((await pending).ok,false);});
test('lost response retry across reload resolves exact prior receipt once',async()=>{const p=harness();p.cloud.loseReplyAfterCommit=true;const first=await p.finish();assert.equal(p.cloud.get(record('receipt-one')).items[0].qty,9);p.cloud.loseReplyAfterCommit=false;const reloaded=harness({cloud:p.cloud,storage:p.storage});const retry=await reloaded.finish({data:{...p.input.data,timestamp:999}});assert.equal(retry.ok,true);assert.equal(p.cloud.paths('/receipts/').length,1);assert.equal(p.cloud.get(record('receipt-one')).timestamp,100);assert.equal(p.cloud.paths('/actionLog/').length,1);});
test('local storage full blocks starting final transaction',async()=>{const p=harness();p.storage.full=true;assert.equal((await p.finish()).ok,false);assert.equal(p.cloud.transactions,0);assert.equal(p.cloud.server.size,0);});
test('offline finish preserves content and does not make cloud writes',async()=>{const p=harness();p.client.setOnline(false);assert.equal((await p.finish()).ok,false);assert.equal(p.cloud.server.size,0);assert.equal(p.input.data.items[0].qty,9);});
test('retry after unresolved attempt and local edit never submits stale old payload',async()=>{const p=harness();p.cloud.reject='unavailable';assert.equal((await p.finish()).ok,false);p.cloud.reject=null;p.state.fp='edited-fingerprint';const result=await p.finish({fingerprint:p.state.fp,data:{...p.input.data,items:[{productId:'milk',qty:17}]}});assert.equal(result.ok,false);assert.equal(p.cloud.get(record('receipt-one')),null);});
test('extras conflict prevents receipt, price and audit commit',async()=>{const p=harness();p.cloud.put(product('milk'),{price:5});p.cloud.put(root.concat('papers','paper_1').join('/'),{captureId:'other',rows:[{qty:99}]});assert.equal((await p.finish({prices:[{id:'milk',expected:5,price:6}],extras:[{collection:'papers',id:'paper_1',data:{captureId:'mine',rows:[{qty:9}]}}]})).ok,false);assert.equal(p.cloud.get(record('receipt-one')),null);assert.equal(p.cloud.get(product('milk')).price,5);assert.equal(p.cloud.paths('/actionLog/').length,0);});
test('receipt paper and scan extras commit atomically',async()=>{const p=harness();assert.equal((await p.finish({extras:[{collection:'papers',id:'paper_1',data:{captureId:'mine',rows:[{qty:9}]}},{collection:'paperScans',id:'paper_1',data:{scan:'paid-result'}}]})).ok,true);assert.equal(p.cloud.get(root.concat('papers','paper_1').join('/')).rows[0].qty,9);assert.equal(p.cloud.get(root.concat('paperScans','paper_1').join('/')).scan,'paid-result');});
for(const code of ['permission-denied','invalid-argument']) test('definitive SDK rejection '+code+' releases immutable pending journal',async()=>{const p=harness();p.cloud.reject=code;const result=await p.finish();assert.equal(result.ok,false);assert.equal(p.engine.pending(p.input.sessionId),false);assert.equal(p.cloud.get(record('receipt-one')),null);});
test('exact replay after legitimate later record edit cannot overwrite or clear',async()=>{const p=harness();assert.equal((await p.finish()).ok,true);const original=p.cloud.get(record('receipt-one'));p.cloud.put(record('receipt-one'),{...original,shortCreditUnits:3});const result=await p.finish();assert.equal(result.ok,false);assert.equal(p.cloud.get(record('receipt-one')).shortCreditUnits,3);});
test('cleanup journal removal failure remains idempotent after reload',async()=>{const p=harness();assert.equal((await p.finish()).ok,true);p.storage.full=true;assert.equal(p.engine.forget(p.input.sessionId),false);p.storage.full=false;const reloaded=harness({cloud:p.cloud,storage:p.storage});assert.equal((await reloaded.finish()).ok,true);assert.equal(p.cloud.paths('/receipts/').length,1);assert.equal(p.cloud.paths('/actionLog/').length,1);});
